# Generated by Django 5.1 on 2024-10-16 18:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$')], verbose_name='CPF')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('upag', models.CharField(max_length=50, verbose_name='UPAG')),
                ('matricula_instituidor', models.CharField(blank=True, max_length=50, null=True)),
                ('situacao_funcional', models.CharField(max_length=50, verbose_name='Situação Funcional')),
                ('rjur', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('rf_situacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Situação RF')),
                ('numero_beneficio_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Benefício 1')),
                ('especie_beneficio_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Espécie do Benefício 1')),
                ('siape_tipo_siape', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo SIAPE')),
                ('siape_qtd_matriculas', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de Matrículas SIAPE')),
                ('siape_qtd_contratos', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de Contratos SIAPE')),
                ('flg_nao_perturbe', models.BooleanField(default=False, verbose_name='Não Perturbe')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(default='Ranking Geral', max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setor', models.CharField(max_length=100)),
                ('range_data_inicio', models.DateField()),
                ('range_data_final', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario_id', models.PositiveIntegerField()),
                ('cpf_cliente', models.CharField(blank=True, max_length=11, null=True)),
                ('valor_est', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebitoMargem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('orgao', models.CharField(max_length=50, verbose_name='Órgão')),
                ('matricula', models.CharField(max_length=50, verbose_name='Matrícula')),
                ('upag', models.PositiveIntegerField(verbose_name='UPAG')),
                ('pmt', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PMT')),
                ('prazo', models.PositiveIntegerField(verbose_name='Prazo')),
                ('contrato', models.CharField(max_length=50, verbose_name='Contrato')),
                ('saldo_5', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo 5')),
                ('beneficio_5', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Benefício 5')),
                ('benef_util_5', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Benefício Utilizado 5')),
                ('benef_saldo_5', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Benefício 5')),
                ('bruta_35', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bruta 35')),
                ('util_35', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Utilizado 35')),
                ('saldo_35', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo 35')),
                ('bruta_70', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bruta 70')),
                ('saldo_70', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo 70')),
                ('rend_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rendimento Bruto')),
                ('data_envio', models.DateTimeField(auto_now_add=True, null=True)),
                ('nome_campanha', models.CharField(max_length=100, verbose_name='Nome da Campanha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitos_margens', to='siape.cliente')),
            ],
            options={
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='InformacoesPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('fne_celular_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular 1')),
                ('fne_celular_1_flg_whats', models.BooleanField(default=False, verbose_name='Celular 1 tem WhatsApp')),
                ('fne_celular_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular 2')),
                ('fne_celular_2_flg_whats', models.BooleanField(default=False, verbose_name='Celular 2 tem WhatsApp')),
                ('end_cidade_1', models.CharField(max_length=100, verbose_name='Cidade')),
                ('email_1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 1')),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 2')),
                ('email_3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 3')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes_pessoais', to='siape.cliente')),
            ],
            options={
                'ordering': ['-data_envio'],
            },
        ),
    ]
