# Generated by Django 5.1 on 2024-08-28 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('uf', models.CharField(max_length=2)),
                ('upag', models.CharField(max_length=50)),
                ('matricula_instituidor', models.CharField(blank=True, max_length=50, null=True)),
                ('situacao_funcional', models.CharField(max_length=50)),
                ('rjur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(default='Ranking Geral', max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setor', models.CharField(max_length=100)),
                ('range_data_inicio', models.DateField()),
                ('range_data_final', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario_id', models.PositiveIntegerField()),
                ('cpf_cliente', models.CharField(blank=True, max_length=11, null=True)),
                ('valor_est', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaDebitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('rubrica', models.CharField(blank=True, max_length=50, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('orgao', models.CharField(blank=True, max_length=100, null=True)),
                ('pmt', models.FloatField(blank=True, null=True)),
                ('prazo', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('exc_soma', models.FloatField(blank=True, null=True)),
                ('margem', models.FloatField(blank=True, null=True)),
                ('base_calc', models.FloatField(blank=True, null=True)),
                ('bruta_5', models.FloatField(blank=True, null=True)),
                ('utilz_5', models.FloatField(blank=True, null=True)),
                ('saldo_5', models.FloatField(blank=True, null=True)),
                ('beneficio_bruta_5', models.FloatField(blank=True, null=True)),
                ('beneficio_utilizado_5', models.FloatField(blank=True, null=True)),
                ('beneficio_saldo_5', models.FloatField(blank=True, null=True)),
                ('bruta_35', models.FloatField(blank=True, null=True)),
                ('utilz_35', models.FloatField(blank=True, null=True)),
                ('saldo_35', models.FloatField(blank=True, null=True)),
                ('bruta_70', models.FloatField(blank=True, null=True)),
                ('utilz_70', models.FloatField(blank=True, null=True)),
                ('saldo_70', models.FloatField(blank=True, null=True)),
                ('creditos', models.FloatField(blank=True, null=True)),
                ('debitos', models.FloatField(blank=True, null=True)),
                ('liquido', models.FloatField(blank=True, null=True)),
                ('arq_upag', models.CharField(blank=True, max_length=50, null=True)),
                ('exc_qtd', models.IntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='siape.cliente')),
            ],
        ),
    ]
