# Generated by Django 5.1 on 2024-11-04 19:23

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Campanha'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rjur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='situacao_funcional',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Situação Funcional'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='upag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UPAG'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='benef_saldo_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo Benefício 5'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='benef_util_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Benefício Utilizado 5'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='beneficio_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Benefício 5'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='bruta_35',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bruta 35'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='bruta_70',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bruta 70'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='contrato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='orgao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Órgão'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='pmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PMT'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='prazo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='saldo_35',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo 35'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='saldo_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo 5'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='saldo_70',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo 70'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='upag',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='UPAG'),
        ),
        migrations.AlterField(
            model_name='debitomargem',
            name='util_35',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Utilizado 35'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='end_cidade_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='fne_celular_1_flg_whats',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Celular 1 tem WhatsApp'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='fne_celular_2_flg_whats',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Celular 2 tem WhatsApp'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='registermeta',
            name='range_data_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registermeta',
            name='range_data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registermeta',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registermeta',
            name='tipo',
            field=models.CharField(blank=True, choices=[('GERAL', 'Geral - Todas as equipes'), ('EQUIPE', 'Equipe - Setor específico')], default='GERAL', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='registermeta',
            name='titulo',
            field=models.TextField(blank=True, default='Ranking Geral', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registermeta',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registermoney',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='registermoney',
            name='valor_est',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
