# Generated by Django 5.1 on 2024-11-12 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_carteira_de_trabalho_and_more'),
        ('siape', '0002_alter_campanha_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermoney',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funcionarios.loja'),
        ),
    ]
