# Generated by Django 5.1 on 2024-10-21 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0002_campanha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitomargem',
            name='nome_campanha',
        ),
        migrations.AddField(
            model_name='debitomargem',
            name='campanha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='debitos_margens', to='siape.campanha'),
            preserve_default=False,
        ),
    ]
