# Generated by Django 5.1 on 2024-10-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0003_remove_debitomargem_nome_campanha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitomargem',
            name='data_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registermoney',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
