# Generated by Django 5.1 on 2024-10-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('siape', '0004_alter_debitomargem_data_envio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermoney',
            name='funcionario_id',
        ),
        migrations.AddField(
            model_name='registermoney',
            name='funcionario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario'),
            preserve_default=False,
        ),
    ]
