# Generated by Django 5.1 on 2024-10-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0005_remove_registermoney_funcionario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermeta',
            name='tipo',
            field=models.CharField(choices=[('GERAL', 'Geral - Todas as equipes'), ('EQUIPE', 'Equipe - Setor específico')], default='GERAL', max_length=6),
        ),
        migrations.AlterField(
            model_name='registermeta',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
