# Generated by Django 5.1 on 2024-10-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0006_registermeta_tipo_alter_registermeta_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermeta',
            name='loja',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
