# Generated by Django 5.1 on 2024-11-04 14:00

import apps.funcionarios.models
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('horario_entrada', models.TimeField()),
                ('horario_saida', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Horários',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'Cargos',
                'unique_together': {('nome', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departamento', to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='lojas/logos/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='funcionarios.empresa')),
            ],
            options={
                'verbose_name_plural': 'Lojas',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('data_de_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=200, null=True)),
                ('celular', models.CharField(blank=True, max_length=200, null=True)),
                ('celular_sms', models.BooleanField(blank=True, default=False, null=True)),
                ('celular_ligacao', models.BooleanField(blank=True, default=False, null=True)),
                ('celular_whatsapp', models.BooleanField(blank=True, default=False, null=True)),
                ('nome_do_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_da_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=200, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=200, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('pis', models.CharField(blank=True, max_length=20, null=True)),
                ('cnh', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria_cnh', models.CharField(blank=True, max_length=200, null=True)),
                ('ctps', models.CharField(blank=True, max_length=200, null=True)),
                ('matricula', models.CharField(blank=True, max_length=20000, null=True)),
                ('status', models.CharField(default='Ativo', max_length=10)),
                ('data_de_admissao', models.DateField(blank=True, null=True)),
                ('numero_da_folha', models.CharField(blank=True, max_length=200, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=apps.funcionarios.models.get_funcionario_upload_path)),
                ('identidade', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.5\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path)),
                ('carteira_de_trabalho', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.5\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path)),
                ('comprovante_de_escolaridade', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.5\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path)),
                ('pdf_contrato', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.5\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path)),
                ('certidao_de_nascimento', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.5\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.cargo')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.departamento')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.empresa')),
                ('superior_direto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='funcionarios.funcionario')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.horario')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.loja')),
            ],
            options={
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
