# Generated by Django 5.1 on 2024-11-11 13:30

import apps.funcionarios.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionario_carteira_de_trabalho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='carteira_de_trabalho',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.5\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='certidao_de_nascimento',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.5\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='comprovante_de_escolaridade',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.5\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='identidade',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.5\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='pdf_contrato',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.5\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path),
        ),
    ]
