# Generated by Django 5.1 on 2024-09-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionario_bairro_alter_funcionario_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
