# Generated by Django 5.1 on 2024-09-18 13:44

import apps.funcionarios.models
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_genero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name_plural': 'Horários'},
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='carteira_de_trabalho',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.0\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='categoria_cnh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='celular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='celular_ligacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='celular_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='celular_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='certidao_de_nascimento',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.0\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='comprovante_de_escolaridade',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.0\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ctps',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.departamento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.empresa'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.funcionarios.models.get_funcionario_upload_path),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.horario'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='identidade',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.0\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='numero_da_folha',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='pdf_contrato',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PC\\Desktop\\Money\\v4.0\\Sistema-Money\\media\\files_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='pis',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
