# Generated by Django 5.1 on 2024-09-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_alter_cargo_options_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='celular_ligacao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='celular_sms',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='celular_whatsapp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_de_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='pis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
