# Generated by Django 5.1 on 2024-10-16 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('cpf_cliente', models.CharField(max_length=14)),
                ('numero_cliente', models.CharField(blank=True, max_length=15, null=True)),
                ('confirmacao_whatsapp', models.BooleanField(default=True)),
                ('dia_agendado', models.DateTimeField()),
                ('tabulacao_atendente', models.TextField(blank=True, default='AGENDADO', help_text='Até 8 palavras', max_length=200, null=True)),
                ('tabulacao_vendedor', models.TextField(blank=True, help_text='Até 8 palavras', max_length=200, null=True)),
                ('observacao_vendedor', models.TextField(blank=True, null=True)),
                ('atendente_agendou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='funcionarios.funcionario')),
                ('loja_agendada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.loja')),
                ('vendedor_loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='funcionarios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='LogAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('agendamento_id', models.CharField(help_text='ID do agendamento relacionado', max_length=50)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Log de Alteração',
                'verbose_name_plural': 'Logs de Alteração',
            },
        ),
    ]
