# Generated by Django 5.1 on 2024-10-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='observacao_atendente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
