# Generated by Django 5.1 on 2024-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cliente_rua',
            field=models.BooleanField(default=False),
        ),
    ]
