# Generated by Django 5.1 on 2024-09-12 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionario_bairro_alter_funcionario_celular_and_more'),
        ('inss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='data_fim',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='comparecimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='confirmacao_agem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_confim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='funcionario_atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='negocio_fechado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='numero_celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tem_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='funcionarios.funcionario'),
        ),
    ]
