# Generated by Django 5.1 on 2024-11-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inss', '0002_agendamento_cliente_rua'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='mensagem_update_tac',
            field=models.TextField(blank=True, null=True),
        ),
    ]
