# Generated by Django 5.1 on 2024-11-19 17:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_carteira_de_trabalho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Equipe')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equipes/logos/', verbose_name='Logo da Equipe')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('status', models.BooleanField(default=True, verbose_name='Equipe Ativa')),
                ('lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_lideradas', to='funcionarios.funcionario', verbose_name='Líder da Equipe')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_participacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Participação')),
                ('pontos_obtidos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pontos Obtidos')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Participação em Prova',
                'verbose_name_plural': 'Participações em Provas',
            },
        ),
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pontos')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo da Pontuação')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Registro')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to='geral.equipe', verbose_name='Equipe')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Pontuação',
                'verbose_name_plural': 'Pontuações',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='ProvaGincana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Prova')),
                ('descricao', models.TextField(verbose_name='Descrição da Prova')),
                ('pontos_possiveis', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Pontos Possíveis')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Término')),
                ('icone', models.CharField(default='fa-star', max_length=50, verbose_name='Ícone FontAwesome')),
                ('status', models.BooleanField(default=True, verbose_name='Prova Ativa')),
                ('participantes', models.ManyToManyField(related_name='provas_participadas', through='geral.ParticipacaoProva', to='funcionarios.funcionario', verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Prova da Gincana',
                'verbose_name_plural': 'Provas da Gincana',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='participacaoprova',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geral.provagincana', verbose_name='Prova'),
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Entrada')),
                ('ativo', models.BooleanField(default=True, verbose_name='Membro Ativo')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='geral.equipe', verbose_name='Equipe')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_equipe', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Membro de Equipe',
                'verbose_name_plural': 'Membros de Equipe',
                'unique_together': {('funcionario', 'equipe')},
            },
        ),
    ]
